### ISSUE TITLE
(QUESTION) is starting a game possible yet?

### ISSUE THREAD

**Issue by danielah05** [Stovent/CeDImu#10]
emulator is looking very promising so far! but i was wondering if booting up a game is possible or not.
i have the bios fully setup and running, but i havent been able to figure out how to load any roms, opening any cd-i rom through "open disc" does not seem to do anything, even when being in the bios itself nothing happens.

**Comment by Stovent** [comment]
Unfortunately CeDImu can't play discs yet. Opening a disc with "open disc" loads it in the emulator and allows you to use the export functions in "CD-I > Export *", but the chips that controls the disc are not emulated yet.

**Comment by danielah05** [comment]
ah okay, thanks for the answer!
