### ISSUE TITLE
[BUG] Infinite loop when selecting invalid disc

### ISSUE THREAD

**Issue by arp242** [Stovent/CeDImu#2]
If you select an invalid ROM from "file" -> "Open ROM" (I thought you had to select the BIOS there 😅) `CDIDisc::LoadFileSystem()` gets stuck in an infinite loop in the `while((Tell() % 2352) < 2072)` loop. `Tell()` returns `-1`, which presumably indicates some failure, but it never checks for this.

I never really did any C++, so no patch, but should be an easy fix.

Commit f8a79a1 (current master) on Linux.

**Comment by arp242** [comment]
Also happens if you load the .cue file instead of the .bin file btw.

**Comment by Stovent** [comment]
This is old code that isn't error-proof, it will be in the future

I don't support .cue files, I should remove it from the dialog window until I support them.
