### ISSUE TITLE
Binary prebuild downloads [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by sionisaac** [Stovent/CeDImu#6]
Would it be possible to include a prebuilt binary especially for Windows platforms.  The instructions for building on Windows are a little lacking.  Having a prebuild would allow more users to test and report bugs.

Is this emulator limited to Windows/Xwindows shells?  I've built on Linux on my raspberry pi 400 but it can only be run from X not terminal.  Will it be limited to those environments or will it be possible to use it in others?  Retroarch springs to mind since the git mentions MAME.  It would be nice to build a dedicated CDI box on a Linux system and it would clear some space (my cdi220 and 450 take up a lot of space not to mention all the disks lying around).

I look forward to any advancements in this emulator with great enthusiasm.  It's good to know people are still interested in CDI.

**Comment by Stovent** [comment]
Thank you for your interest! 
The project is not really open for testing yet, as it cannot play discs yet, and the user interface may still change in the future.

> it can only be run from X not terminal.

I'm not sure what you mean here, but since it has a GUI application, you need a window system to use it. If you tried to run it from a terminal remotely in SSH, it cannot work because the terminal is not capable of displaying GUI apps.
I've successfully built and run it on my pi 3 a while ago, I ran it by adding a monitor, keyboard and mouse to my Pi, so it had a GUI.
I still maintain x86_64 Linux builds and test them in WSL2, you can find them in the "Actions" page on top.

**Comment by sionisaac** [comment]
Thanks for the response.  I meant that would it be possible to use this emulator in a non windows environment something like retropie or through retroarch since MAME was mentioned.  But I think you've answered my question.  It's not clear how to build on Windows it just says to use cmake.  Could you give some more detailed instructions or possibly a build of the latest snapshot.  I would be happy to setup a built environment in Windows if I knew how.

**Comment by Stovent** [comment]
I've never used retropie or retroarch so I can't tell how they work, but CeDImu is primary built as a library containing all the CD-i emulation. Anybody can use it to provide their own GUI on top of it.

I'm planning to add Windows builds to the "Actions" page, but automating this setup is a bit complicated to me, as I'm unfamiliar with github actions and CI in general. In linux it's easy, as the compiler is already integrated in the base OS, and installing depencies takes just one command.
For Windows my own setup includes building myself the GUI library, but it takes time and there are maybe better solutions so I'll have to look for it.

For Windows you need to have a C++ compiler (I use MinGW), and wxWidgets built as a static library. If you can I recommend building it yourself, but if you can't you'll need to find pre-built versions compatible with your compiler.
Once you have wxWidgets built, use CMake to build CeDImu. I think it's easier to use cmake-gui for this as you have to specify the location of wxWidgets on your machine. If configured correctly you'll be able to generate the Makefile, and finally compile CeDImu with the makefile.

The process is kind of complicated, I'm searching for ways to ease it and to add CI.

**Comment by Stovent** [comment]
I've finally managed to build CeDImu on Windows using MSVC, allowing for github actions CI, along with Linux build and MacOS thanks to @h3x4d3c1m4l. I've also updated the README to include build instructions on Windows
